import { TestItem } from '../playwright/testItem';
import { readFileSync, existsSync } from 'fs';
import { LoggerFactory, Logger } from '../logger/logger';
import { PROJECT_CONFIGS_FILE } from '../constants';

const logger: Logger = LoggerFactory.getLogger('utils.project-config-loader');

export interface ProjectConfig {
  name: string;
  testItem: TestItem;
}

interface SerializedProjectConfig {
  name: string;
  testItem: any; // JSON representation of TestItem
}

/**
 * Load pre-generated project configurations from file
 * Configurations are generated by scripts/generateProjectConfig.ts before Playwright runs
 */
export function loadProjectConfigurations(): ProjectConfig[] {
  const configFilePath = PROJECT_CONFIGS_FILE;
  
  if (!existsSync(configFilePath)) {
    logger.error(`Project configuration file not found: ${configFilePath}`);
    logger.error('Run: npm run generate-config');
    throw new Error('Project configurations not generated. Run the generate-config script first.');
  }

  try {
    const data = readFileSync(configFilePath, 'utf-8');
    const serializedConfigs: SerializedProjectConfig[] = JSON.parse(data);

    const projectConfigs = serializedConfigs.map(config => ({
      name: config.name,
      testItem: TestItem.fromJSON(config.testItem)
    }));

    return projectConfigs;

  } catch (error) {
    logger.error(`Failed to load project configurations: ${error}`);
    throw new Error('Failed to load project configurations from file');
  }
}

/**
 * Extract TestItem instances from project configurations
 */
export function getTestItems(projectConfigs: ProjectConfig[]): TestItem[] {
  return projectConfigs.map(config => config.testItem);
} 