/**
 * Enum for Jenkins credential names
 * Centralizes credential naming to avoid string duplication
 */
export enum Credential {
  COSIGN_PUBLIC_KEY = 'COSIGN_PUBLIC_KEY',
  TUF_MIRROR = 'TUF_MIRROR',
  REKOR_HOST = 'REKOR_HOST',
  ROX_CENTRAL_ENDPOINT = 'ROX_CENTRAL_ENDPOINT',
  ROX_API_TOKEN = 'ROX_API_TOKEN',
  COSIGN_SECRET_KEY = 'COSIGN_SECRET_KEY',
  COSIGN_SECRET_PASSWORD = 'COSIGN_SECRET_PASSWORD',
  GITOPS_AUTH_PASSWORD = 'GITOPS_AUTH_PASSWORD',
  GITOPS_AUTH_USERNAME = 'GITOPS_AUTH_USERNAME',
  IMAGE_REGISTRY_PASSWORD = 'IMAGE_REGISTRY_PASSWORD',
  TRUSTIFICATION_BOMBASTIC_API_URL = 'TRUSTIFICATION_BOMBASTIC_API_URL',
  TRUSTIFICATION_OIDC_ISSUER_URL = 'TRUSTIFICATION_OIDC_ISSUER_URL',
  TRUSTIFICATION_OIDC_CLIENT_ID = 'TRUSTIFICATION_OIDC_CLIENT_ID',
  TRUSTIFICATION_OIDC_CLIENT_SECRET = 'TRUSTIFICATION_OIDC_CLIENT_SECRET',
  TRUSTIFICATION_SUPPORTED_CYCLONEDX_VERSION = 'TRUSTIFICATION_SUPPORTED_CYCLONEDX_VERSION',
  IMAGE_REGISTRY_USER = 'IMAGE_REGISTRY_USER',
  CUSTOM_ROOT_CA = 'CUSTOM_ROOT_CA',
}
