/**
 * Enum for Jenkins credential names
 * Centralizes credential naming to avoid string duplication
 */
export enum JenkinsCredential {
  ROX_API_TOKEN = 'ROX_API_TOKEN',
  COSIGN_SECRET_KEY = 'COSIGN_SECRET_KEY',
  COSIGN_SECRET_PASSWORD = 'COSIGN_SECRET_PASSWORD',
  GITOPS_AUTH_PASSWORD = 'GITOPS_AUTH_PASSWORD',
  IMAGE_REGISTRY_PASSWORD = 'IMAGE_REGISTRY_PASSWORD',
  TRUSTIFICATION_BOMBASTIC_API_URL = 'TRUSTIFICATION_BOMBASTIC_API_URL',
  TRUSTIFICATION_OIDC_ISSUER_URL = 'TRUSTIFICATION_OIDC_ISSUER_URL',
  TRUSTIFICATION_OIDC_CLIENT_ID = 'TRUSTIFICATION_OIDC_CLIENT_ID',
  TRUSTIFICATION_OIDC_CLIENT_SECRET = 'TRUSTIFICATION_OIDC_CLIENT_SECRET',
  TRUSTIFICATION_SUPPORTED_CYCLONEDX_VERSION = 'TRUSTIFICATION_SUPPORTED_CYCLONEDX_VERSION',
}
